chat:
  - notbadai_chat
  - notbadai_tools_chat
apply: notbadai_apply
symbol_lookup: notbadai_lookup
autocomplete: notbadai_autocomplete
diff:
  min_collapse_lines: 3
  min_auto_collapse_lines: 5
  context_lines: 2
  ignore_whitespace: false
port: 7527
host: localhost
python_path:
tools:
  - name: "source control"
    extension: "notbadai_commit"
    description: "A git commit tool"
  - name: "inline completions"
    extension: "notbadai_inline_completion"
    shortcut: "ctrl+m"
  - name: "find errors"
    extension: "notbadai_errors"
    shortcut: "cmd+e"
  - name: "code format"
    extension: "notbadai_format"
    shortcut: "cmd+l"
  - name: "modify code"
    extension: "notbadai_modify"
    shortcut: "ctrl+,"
api_providers:
  - provider: "openrouter"
    key: ""
    default: true
